### ISSUE TITLE
add more_itertools to requirements.txt

### ISSUE THREAD

**Issue by slabasan** [LLNL/thicket#152]
```
File thicket/thicket/helpers.py:6, in <module>
      1 # Copyright 2022 Lawrence Livermore National Security, LLC and other
      2 # Thicket Project Developers. See the top-level LICENSE file for details.
      3 #
      4 # SPDX-License-Identifier: MIT
----> 6 from more_itertools import powerset
      7 import pandas as pd
     10 def _are_synced(gh, df):

ModuleNotFoundError: No module named 'more_itertools'
```

**Comment by ilumsden** [comment]
@michaelmckinsey1 add it to `setup.py` first and foremost. If this dependency is not in `setup.py`, it will not be visible to any `pip` installs.

**Comment by michaelmckinsey1** [comment]
`more-itertools` is in `setup.py` https://github.com/LLNL/thicket/blob/develop/setup.py#L50. @slabasan Maybe you were running on an environment that was installed before #145 was merged (April 9)? In which case you just need to `pip install more-itertools` in that environment. Any new environments installing Thicket will have `more-itertools`.
