### ISSUE TITLE
RADIUSS Tutorial Reflection

### ISSUE THREAD

**Issue by slabasan** [LLNL/thicket#81]
* Update rendered tutorial notebooks in thicket
* Update tutorials page with materials
* Rendered basic tutorial is using new RAJAPerf data, this shouldn't be the case yet because we want to update all
* Use display instead of print for dataframes, will all columns of dataframe render?

**Comment by ilumsden** [comment]
The following PRs fix a lot of the syncing between the Thicket `docs/` directory and the tutorial repo:
* #100 
* LLNL/thicket-tutorial#25

Also, regarding `display` and `print`, we should definitely be using `display` for DataFrames. However, when running in Jupyter, there is no need to manually invoke the `display` function. When run as Jupyter cells, the following pieces of code are equivalent:

Explicit `display`:
```python
df = pd.DataFrame(...)
...
display(df)
```

Implicit `display`:
```python
df = pd.DataFrame(...)
...
df
```

Also, when running in Jupyter, there is no need to manually import `display` from `IPython.display`. The `display` function is auto-imported by Jupyter.

**Comment by slabasan** [comment]
Several PRs resolve this issue: #121 #120 #119 #117
